// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using daedalus.Server.Database;

namespace daedalus.Server.Migrations
{
    [DbContext(typeof(daedalusDBContext))]
    [Migration("20210418152815_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("daedalus.Server.Database.Condition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("AltitudeCentimeters")
                        .HasColumnType("REAL");

                    b.Property<double>("DegreesCelsius")
                        .HasColumnType("REAL");

                    b.Property<double>("HumidityPercentage")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("PressureMillibars")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Conditions");
                });
#pragma warning restore 612, 618
        }
    }
}
